/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simul1d_dpush1d */

#ifndef _Included_simul1d_dpush1d
#define _Included_simul1d_dpush1d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simul1d_dpush1d
 * Method:    dmjpost
 * Signature: ([D[DID[DIIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_dpush1d_dmjpost
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jdouble, jdoubleArray, jint, jint, jint, jint);

/*
 * Class:     simul1d_dpush1d
 * Method:    dcjpost
 * Signature: ([D[D[D[D[D[DDIDDD[DIIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_dpush1d_dcjpost
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jint, jdouble, jdouble, jdouble, jdoubleArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
