/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simul1d_init1d */

#ifndef _Included_simul1d_init1d
#define _Included_simul1d_init1d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simul1d_init1d
 * Method:    distr
 * Signature: ([DIIDDIIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_init1d_distr
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jdouble, jdouble, jint, jint, jint, jint);

/*
 * Class:     simul1d_init1d
 * Method:    distrh
 * Signature: ([DIIDDDDDDIIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_init1d_distrh
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jint, jint, jint);

/*
 * Class:     simul1d_init1d
 * Method:    fdistr
 * Signature: ([DIIDDDIIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_init1d_fdistr
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jdouble, jdouble, jdouble, jint, jint, jint, jint);

/*
 * Class:     simul1d_init1d
 * Method:    vdistr
 * Signature: ([DIIDDI)V
 */
JNIEXPORT void JNICALL Java_simul1d_init1d_vdistr
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jdouble, jdouble, jint);

/*
 * Class:     simul1d_init1d
 * Method:    vdistrh
 * Signature: ([DIIDDDDDDI)V
 */
JNIEXPORT void JNICALL Java_simul1d_init1d_vdistrh
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     simul1d_init1d
 * Method:    bdistr
 * Signature: ([D[DIDIIIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_init1d_bdistr
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
