/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simul1d_diag1d */

#ifndef _Included_simul1d_diag1d
#define _Included_simul1d_diag1d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simul1d_diag1d
 * Method:    writebf
 * Signature: ([DI[I[ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_writebf
  (JNIEnv *, jclass, jdoubleArray, jint, jintArray, jintArray, jstring, jint);

/*
 * Class:     simul1d_diag1d
 * Method:    readbf
 * Signature: ([DII[I[ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_readbf
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jintArray, jintArray, jstring, jint);

/*
 * Class:     simul1d_diag1d
 * Method:    writebfv
 * Signature: ([DI[I[ILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_writebfv
  (JNIEnv *, jclass, jdoubleArray, jint, jintArray, jintArray, jstring, jint, jint);

/*
 * Class:     simul1d_diag1d
 * Method:    readbfv
 * Signature: ([DII[I[ILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_readbfv
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jintArray, jintArray, jstring, jint, jint);

/*
 * Class:     simul1d_diag1d
 * Method:    writebfc
 * Signature: ([DI[I[ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_writebfc
  (JNIEnv *, jclass, jdoubleArray, jint, jintArray, jintArray, jstring, jint);

/*
 * Class:     simul1d_diag1d
 * Method:    readbfc
 * Signature: ([DII[I[ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_readbfc
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jintArray, jintArray, jstring, jint);

/*
 * Class:     simul1d_diag1d
 * Method:    writebfvc
 * Signature: ([DI[I[ILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_writebfvc
  (JNIEnv *, jclass, jdoubleArray, jint, jintArray, jintArray, jstring, jint, jint);

/*
 * Class:     simul1d_diag1d
 * Method:    readbfvc
 * Signature: ([DII[I[ILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_readbfvc
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jintArray, jintArray, jstring, jint, jint);

/*
 * Class:     simul1d_diag1d
 * Method:    writef
 * Signature: ([DI[ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_writef
  (JNIEnv *, jclass, jdoubleArray, jint, jintArray, jstring);

/*
 * Class:     simul1d_diag1d
 * Method:    vdist
 * Signature: ([D[D[DIIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_vdist
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jint, jint);

/*
 * Class:     simul1d_diag1d
 * Method:    fgetunit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_simul1d_diag1d_fgetunit
  (JNIEnv *, jclass, jint);

/*
 * Class:     simul1d_diag1d
 * Method:    fbfopen
 * Signature: ([DII[ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_fbfopen
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jintArray, jstring);

/*
 * Class:     simul1d_diag1d
 * Method:    fbfvopen
 * Signature: ([DIII[ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_fbfvopen
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jint, jintArray, jstring);

/*
 * Class:     simul1d_diag1d
 * Method:    fbfcopen
 * Signature: ([DII[ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_fbfcopen
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jintArray, jstring);

/*
 * Class:     simul1d_diag1d
 * Method:    fbfvcopen
 * Signature: ([DIII[ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_fbfvcopen
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jint, jintArray, jstring);

/*
 * Class:     simul1d_diag1d
 * Method:    frclose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_frclose
  (JNIEnv *, jclass, jint);

/*
 * Class:     simul1d_diag1d
 * Method:    frwnml1
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[D[Ljava/lang/String;II[I[I[I)V
 */
JNIEXPORT void JNICALL Java_simul1d_diag1d_frwnml1
  (JNIEnv *, jclass, jstring, jstring, jobjectArray, jdoubleArray, jobjectArray, jint, jint, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
