/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simul1d_field1d */

#ifndef _Included_simul1d_field1d
#define _Included_simul1d_field1d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simul1d_field1d
 * Method:    cguard
 * Signature: ([DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_cguard
  (JNIEnv *, jclass, jdoubleArray, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    dguard
 * Signature: ([DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_dguard
  (JNIEnv *, jclass, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    scguard
 * Signature: ([DDDII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_scguard
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    sguard
 * Signature: ([DDII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_sguard
  (JNIEnv *, jclass, jdoubleArray, jdouble, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    acguard
 * Signature: ([DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_acguard
  (JNIEnv *, jclass, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    aguard
 * Signature: ([DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_aguard
  (JNIEnv *, jclass, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    pois_init
 * Signature: ([DDDI)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_pois_1init
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jint);

/*
 * Class:     simul1d_field1d
 * Method:    pois
 * Signature: ([D[DI[D[DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_pois
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    bpois
 * Signature: ([D[D[DD[DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_bpois
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    apois
 * Signature: ([D[D[DD[DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_apois
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    ibpois
 * Signature: ([D[D[DD[DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_ibpois
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    maxwel
 * Signature: ([D[D[D[DDD[D[DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_maxwel
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdouble, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    emfield
 * Signature: ([D[D[D[DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_emfield
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    bmfield
 * Signature: ([D[D[DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_bmfield
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    emfieldr
 * Signature: ([D[D[D[DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_emfieldr
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    bmfieldr
 * Signature: ([D[D[DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_bmfieldr
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    avpot
 * Signature: ([D[DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_avpot
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    avrpot
 * Signature: ([D[D[DDII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_avrpot
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    gtmodes
 * Signature: ([D[DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_gtmodes
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    ptmodes
 * Signature: ([D[DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_ptmodes
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    gtvmodes
 * Signature: ([D[DIIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_gtvmodes
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    ptvmodes
 * Signature: ([D[DIIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_ptvmodes
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    sfguard
 * Signature: ([D[DDIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_sfguard
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    dcuperp
 * Signature: ([D[DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_dcuperp
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    adcuperp
 * Signature: ([D[DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_adcuperp
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    epois_init
 * Signature: ([DDDDDI)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_epois_1init
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     simul1d_field1d
 * Method:    epois
 * Signature: ([D[D[DD[DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_epois
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    iepois
 * Signature: ([D[D[DD[DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_iepois
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    wpmxn
 * Signature: ([DDD[D[DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_wpmxn
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    baddext
 * Signature: ([DDDIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_baddext
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    ivrcopy
 * Signature: ([D[DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_ivrcopy
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     simul1d_field1d
 * Method:    ivccopy
 * Signature: ([D[DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_field1d_ivccopy
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
