/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simul1d_push1d */

#ifndef _Included_simul1d_push1d
#define _Included_simul1d_push1d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simul1d_push1d
 * Method:    dpost
 * Signature: ([D[DID[DIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_push1d_dpost
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jdouble, jdoubleArray, jint, jint, jint);

/*
 * Class:     simul1d_push1d
 * Method:    push
 * Signature: ([D[DIDD[D[DIIIII)V
 */
JNIEXPORT void JNICALL Java_simul1d_push1d_push
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jdouble, jdouble, jdoubleArray, jdoubleArray, jint, jint, jint, jint, jint);

/*
 * Class:     simul1d_push1d
 * Method:    sortp
 * Signature: ([D[D[II[I[DII)V
 */
JNIEXPORT void JNICALL Java_simul1d_push1d_sortp
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jintArray, jint, jintArray, jdoubleArray, jint, jint);

/*
 * Class:     simul1d_push1d
 * Method:    dpostgl
 * Signature: ([D[DIDII[DI)V
 */
JNIEXPORT void JNICALL Java_simul1d_push1d_dpostgl
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jdoubleArray, jint);

/*
 * Class:     simul1d_push1d
 * Method:    pushgl
 * Signature: ([D[DIDD[DII[DI)V
 */
JNIEXPORT void JNICALL Java_simul1d_push1d_pushgl
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint, jdouble, jdouble, jdoubleArray, jint, jint, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
